language: node_js
node_js:
  - "5.6.0"

addons:
  code_climate:
    repo_token: b5c3b6fe39b49d2f86b384a4a3af45e6394fc41162bb008ad05f741c9c5117b4

before_install:
  - "export CHROME_BIN=chromium-browser"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

after_script:
  - codeclimate-test-reporter < coverage/**/lcov.info

env:
  - TEST_SCOPE=angular_1.6.x

notifications:
  webhooks: https://webhooks.gitter.im/e/45e7c0327284467c72d0
